//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string Cusname { get; set; }
        public string cusAddress { get; set; }
        public string Product_code { get; set; }
        public string cusphone { get; set; }
        public string Product_Name { get; set; }
    }
}
